"""Draw the name as a signature and write templates/_signature.html.

The wordmark is not set in the webfont any more -- it is an SVG of the actual
glyph outlines, one path per letter, so each letter can be stroked on in
writing order and the name appears to be signed rather than to fade in.

Run this again if the shop is renamed:

    python3 make_signature.py "Some Other Name"

and the template records which name it was drawn for. base.html falls back to
plain webfont text whenever the title no longer matches, so a rename in the
admin degrades quietly instead of signing the wrong name.
"""
import json
import os
import sys

from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen

BASE = os.path.dirname(os.path.abspath(__file__))
FONT = os.path.join(BASE, "static", "fonts", "MrsSaintDelafield-Regular.ttf")
OUT = os.path.join(BASE, "templates", "_signature.html")
META = os.path.join(BASE, "templates", "_signature.json")

# The pen is thin: this face is a fine-nib script and a heavy trace would draw
# a letter fatter than the one it settles into.
STROKE = 11          # font units, ~0.6px at a 54px wordmark
TOTAL = 1.85         # seconds for the whole signature
PAD = 40             # font units of air around the outlines


def build(name):
    f = TTFont(FONT)
    upm = f["head"].unitsPerEm
    gs = f.getGlyphSet()
    cmap = f.getBestCmap()
    hmtx = f["hmtx"]

    # HarfBuzz shaping confirms this face applies no kerning to the name, so a
    # running sum of advances places the glyphs exactly where the browser does.
    glyphs, cursor = [], 0
    for ch in name:
        if ch == " ":
            cursor += hmtx[cmap[ord(" ")]][0] if ord(" ") in cmap else upm // 4
            continue
        if ord(ch) not in cmap:
            return None
        gname = cmap[ord(ch)]
        pen = SVGPathPen(gs)
        gs[gname].draw(pen)
        bounds = BoundsPen(gs)
        gs[gname].draw(bounds)
        glyphs.append({"ch": ch, "d": pen.getCommands(), "x": cursor,
                       "adv": hmtx[gname][0], "bounds": bounds.bounds})
        cursor += hmtx[gname][0]

    xs0 = [g["x"] + g["bounds"][0] for g in glyphs if g["bounds"]]
    xs1 = [g["x"] + g["bounds"][2] for g in glyphs if g["bounds"]]
    ys0 = [g["bounds"][1] for g in glyphs if g["bounds"]]
    ys1 = [g["bounds"][3] for g in glyphs if g["bounds"]]
    x0, x1, y0, y1 = min(xs0) - PAD, max(xs1) + PAD, min(ys0) - PAD, max(ys1) + PAD
    w, h = x1 - x0, y1 - y0

    # A letter's share of the writing time is its share of the width -- the M
    # takes far longer to draw than the t, which is what a hand does too.
    span = sum(g["adv"] for g in glyphs) or 1
    t, parts = 0.0, []
    for i, g in enumerate(glyphs):
        dur = TOTAL * (g["adv"] / span)
        parts.append(
            '  <path class="sg" d="%s" transform="translate(%d 0)" pathLength="1"'
            ' style="--d:%.3fs;--t:%.3fs"/>' % (g["d"], g["x"], dur, t))
        t += dur * 0.86      # a little overlap: the pen does not stop between letters

    # scale(1 -1) flips the font's y-up outlines into SVG's y-down space, so a
    # font point y lands at SVG -y: the top of the drawing is -y1 and the
    # bottom (the y descender) is -y0. The viewBox is stated in those terms.
    svg = (
        '<svg class="wordmark-sig" viewBox="%d %d %d %d" aria-hidden="true" '
        'focusable="false" preserveAspectRatio="xMinYMid meet" '
        'style="--total:%.2fs">\n'
        '  <g transform="scale(1 -1)" fill="currentColor" '
        'stroke="currentColor" stroke-width="%d" stroke-linecap="round" '
        'stroke-linejoin="round">\n%s\n  </g>\n</svg>'
        % (x0, -y1, w, h, TOTAL, STROKE, "\n".join(parts))
    )
    return {"name": name, "svg": svg, "upm": upm, "w": w, "h": h}


def main():
    name = sys.argv[1] if len(sys.argv) > 1 else "McCarthy"
    got = build(name)
    if not got:
        sys.exit("The font has no glyph for one of those characters.")
    with open(OUT, "w") as fh:
        fh.write("{# Generated by make_signature.py -- do not hand-edit. #}\n")
        fh.write(got["svg"] + "\n")
    with open(META, "w") as fh:
        json.dump({"name": name}, fh)
    print("wrote %s for %r  (%dx%d units)" % (OUT, name, got["w"], got["h"]))


if __name__ == "__main__":
    main()
